##SECRET KEY
SECRET_KEY: "anaksoleh"
APP_NAME: "rails-webbapps"

TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhcHBfbmFtZSI6InJhaWxzLXdlYmJhcHBzIiwiZXhwIjoxNjA5MjM0NzcxfQ.BTqhONCk3OPUPPW9IKGgUIpByUDryvC7X7Vcx7JyEIE"

## REDIS
REDIS_HOST: 'localhost'
REDIS_PORT: '6379'

#OMNIAUTH
FACEBOOK_APP_ID: ''
FACEBOOK_APP_SECRET: ''
GITHUB_APP_ID: ''
GITHUB_APP_SECRET: ''
GOOGLE_APP_ID: ''
GOOGLE_APP_SECRET: ''
TWITTER_APP_ID: ''
TWITTER_APP_SECRET: ''